import type { Product, KitProduct, Testimonial, Order } from './types'

export const MOCK_PRODUCTS: Product[] = [
  // OVERSIZED
  {
    id: 'ovs-001',
    slug: 'camiseta-oversized-drop-black',
    name: 'Drop Black Oversized',
    shortDescription: 'Camiseta oversized algodÃ£o premium 300g, corte amplo streetwear',
    description: 'Nossa camiseta oversized premium Ã© feita com algodÃ£o 300g de alta qualidade. Corte amplo inspirado no streetwear contemporÃ¢neo. DisponÃ­vel para personalizaÃ§Ã£o com sua arte ou escolha entre nossas estampas exclusivas.',
    price: 89.90,
    originalPrice: 119.90,
    category: 'oversized',
    images: [
      { id: 'img-001', url: '/images/tshirt-black.svg', alt: 'Drop Black Oversized - Frente', color: '#1A1A1A' },
      { id: 'img-002', url: '/images/tshirt-black-back.svg', alt: 'Drop Black Oversized - Costas', color: '#1A1A1A' },
    ],
    colors: [
      { name: 'Preto', hex: '#1A1A1A' },
      { name: 'Off-White', hex: '#F0EDE6' },
      { name: 'Cinza Chumbo', hex: '#4A4A4A' },
      { name: 'Vermelho', hex: '#CC0000' },
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
      { label: 'XGG', available: false },
    ],
    status: 'available',
    tags: ['bestseller', 'sale'],
    rating: 4.9,
    reviewCount: 347,
    isPersonalizable: true,
    isFeatured: true,
    isNew: false,
    stock: 48,
    sku: 'OVS-001-BLK',
    material: '100% AlgodÃ£o 300g',
    weight: 0.38,
    createdAt: '2024-01-15',
  },
  {
    id: 'ovs-002',
    slug: 'camiseta-oversized-urban-white',
    name: 'Urban White Oversized',
    shortDescription: 'Oversized off-white premium para personalizaÃ§Ã£o total',
    description: 'A favorita para personalizaÃ§Ã£o. AlgodÃ£o off-white premium com caimento perfeito para estampas grandes e arrojadas. O canvas ideal para o seu drop.',
    price: 89.90,
    category: 'oversized',
    images: [
      { id: 'img-003', url: '/images/tshirt-white.svg', alt: 'Urban White Oversized', color: '#F0EDE6' },
    ],
    colors: [
      { name: 'Off-White', hex: '#F0EDE6' },
      { name: 'Creme', hex: '#EDE0CA' },
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
      { label: 'XGG', available: true },
    ],
    status: 'available',
    tags: ['new', 'bestseller'],
    rating: 4.8,
    reviewCount: 219,
    isPersonalizable: true,
    isFeatured: true,
    isNew: true,
    stock: 62,
    sku: 'OVS-002-WHT',
    material: '100% AlgodÃ£o 300g',
    weight: 0.38,
    createdAt: '2024-03-01',
  },
  {
    id: 'ovs-003',
    slug: 'camiseta-oversized-grafite-drop',
    name: 'Grafite Drop Oversized',
    shortDescription: 'O clÃ¡ssico grafite em corte oversized streetwear',
    description: 'Grafite profundo com textura suave. Perfeita para estampas monocromÃ¡ticas ou coloridas. Um must-have em qualquer guarda-roupa streetwear.',
    price: 89.90,
    originalPrice: 99.90,
    category: 'oversized',
    images: [
      { id: 'img-004', url: '/images/tshirt-gray.svg', alt: 'Grafite Drop Oversized', color: '#4A4A4A' },
    ],
    colors: [
      { name: 'Grafite', hex: '#4A4A4A' },
      { name: 'Cinza MÃ©dio', hex: '#888888' },
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: false },
    ],
    status: 'low_stock',
    tags: ['sale'],
    rating: 4.7,
    reviewCount: 156,
    isPersonalizable: true,
    isFeatured: false,
    isNew: false,
    stock: 7,
    sku: 'OVS-003-GRF',
    material: '100% AlgodÃ£o 300g',
    weight: 0.38,
    createdAt: '2024-01-20',
  },
  {
    id: 'ovs-004',
    slug: 'camiseta-oversized-navy-drop',
    name: 'Navy Drop Oversized',
    shortDescription: 'Azul navy premium com corte oversized exclusivo',
    description: 'Azul navy intenso em algodÃ£o premium. Uma cor que combina com tudo e dÃ¡ personalidade a qualquer estampa.',
    price: 94.90,
    category: 'oversized',
    images: [
      { id: 'img-005', url: '/images/tshirt-navy.svg', alt: 'Navy Drop Oversized', color: '#1B2B5E' },
    ],
    colors: [
      { name: 'Navy', hex: '#1B2B5E' },
      { name: 'Azul Royal', hex: '#2244AA' },
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
      { label: 'XGG', available: true },
    ],
    status: 'available',
    tags: ['new'],
    rating: 4.8,
    reviewCount: 89,
    isPersonalizable: true,
    isFeatured: false,
    isNew: true,
    stock: 35,
    sku: 'OVS-004-NVY',
    material: '100% AlgodÃ£o 300g',
    weight: 0.38,
    createdAt: '2024-04-01',
  },

  // CAMISETAS NORMAIS
  {
    id: 'cam-001',
    slug: 'camiseta-classic-black',
    name: 'Classic Black',
    shortDescription: 'Camiseta algodÃ£o 180g corte regular, a base perfeita',
    description: 'A camiseta clÃ¡ssica em preto sÃ³lido. AlgodÃ£o 180g com toque suave. Perfeita para o dia a dia ou como base para personalizaÃ§Ã£o.',
    price: 59.90,
    category: 'camisetas',
    images: [
      { id: 'img-006', url: '/images/tshirt-black.svg', alt: 'Classic Black', color: '#1A1A1A' },
    ],
    colors: [
      { name: 'Preto', hex: '#1A1A1A' },
      { name: 'Branco', hex: '#FFFFFF' },
      { name: 'Cinza', hex: '#888888' },
      { name: 'Vermelho', hex: '#CC0000' },
      { name: 'Navy', hex: '#1B2B5E' },
    ],
    sizes: [
      { label: 'PP', available: true },
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
      { label: 'XGG', available: true },
    ],
    status: 'available',
    tags: ['bestseller'],
    rating: 4.9,
    reviewCount: 512,
    isPersonalizable: true,
    isFeatured: true,
    isNew: false,
    stock: 120,
    sku: 'CAM-001-BLK',
    material: '100% AlgodÃ£o 180g',
    weight: 0.22,
    createdAt: '2023-06-01',
  },

  // DRYFIT
  {
    id: 'dry-001',
    slug: 'camiseta-dryfit-performance-black',
    name: 'Performance Black DryFit',
    shortDescription: 'Tecido dry-fit premium para treinos intensos',
    description: 'Desenvolvida para quem nÃ£o para. Tecido dry-fit de alta performance com tecnologia anti-odor e proteÃ§Ã£o UV50+. RespirÃ¡vel e leve para qualquer treino.',
    price: 79.90,
    category: 'dryfit',
    images: [
      { id: 'img-007', url: '/images/tshirt-dryfit-black.svg', alt: 'Performance Black DryFit', color: '#0D0D0D' },
    ],
    colors: [
      { name: 'Preto', hex: '#0D0D0D' },
      { name: 'Branco', hex: '#F5F5F5' },
      { name: 'Vermelho', hex: '#CC0000' },
      { name: 'Verde Militar', hex: '#4A6741' },
      { name: 'Azul Royal', hex: '#2244AA' },
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: true },
      { label: 'XGG', available: true },
    ],
    status: 'available',
    tags: ['bestseller', 'new'],
    rating: 4.9,
    reviewCount: 283,
    isPersonalizable: false,
    isFeatured: true,
    isNew: true,
    stock: 88,
    sku: 'DRY-001-BLK',
    material: '100% PoliÃ©ster Dry-Fit 150g',
    weight: 0.18,
    createdAt: '2024-02-01',
  },
  {
    id: 'dry-002',
    slug: 'camiseta-dryfit-slim-fit-red',
    name: 'Slim Fit Red DryFit',
    shortDescription: 'Corte slim ajustado para performance e estilo',
    description: 'Para quem quer performance com estilo. Corte slim que valoriza a musculatura sem apertar. Ideal para crossfit, corrida e musculaÃ§Ã£o.',
    price: 79.90,
    category: 'dryfit',
    images: [
      { id: 'img-008', url: '/images/tshirt-dryfit-red.svg', alt: 'Slim Fit Red DryFit', color: '#CC0000' },
    ],
    colors: [
      { name: 'Vermelho', hex: '#CC0000' },
      { name: 'Preto', hex: '#0D0D0D' },
      { name: 'Cinza', hex: '#888888' },
    ],
    sizes: [
      { label: 'P', available: true },
      { label: 'M', available: true },
      { label: 'G', available: true },
      { label: 'GG', available: false },
    ],
    status: 'low_stock',
    tags: ['new'],
    rating: 4.7,
    reviewCount: 94,
    isPersonalizable: false,
    isFeatured: false,
    isNew: true,
    stock: 12,
    sku: 'DRY-002-RED',
    material: '100% PoliÃ©ster Dry-Fit 150g',
    weight: 0.18,
    createdAt: '2024-03-15',
  },

  // PRODUTOS 3D
  {
    id: '3d-001',
    slug: 'chaveiro-3d-personalizado',
    name: 'Chaveiro 3D Personalizado',
    shortDescription: 'Chaveiro impresso em 3D com sua arte ou logotipo',
    description: 'Chaveiros Ãºnicos impressos em 3D com sua arte, logo, personagem ou texto. Material PLA de alta resistÃªncia. MÃ­nimo de 10 unidades para pedidos personalizados.',
    price: 24.90,
    originalPrice: 34.90,
    category: 'produtos-3d',
    subcategory: 'Chaveiros',
    images: [
      { id: 'img-009', url: '/images/3d-keychain.svg', alt: 'Chaveiro 3D Personalizado', color: '#E10600' },
    ],
    colors: [
      { name: 'Vermelho', hex: '#E10600' },
      { name: 'Preto', hex: '#1A1A1A' },
      { name: 'Branco', hex: '#F0F0F0' },
      { name: 'Azul', hex: '#2244AA' },
      { name: 'Verde', hex: '#2A7A2A' },
    ],
    sizes: [{ label: 'Ãšnico', available: true }],
    status: 'available',
    tags: ['bestseller', 'sale'],
    rating: 4.8,
    reviewCount: 167,
    isPersonalizable: true,
    isFeatured: true,
    isNew: false,
    stock: 999,
    sku: '3D-001-CHV',
    material: 'PLA Premium',
    weight: 0.05,
    createdAt: '2024-01-01',
  },
  {
    id: '3d-002',
    slug: 'medalha-3d-personalizada',
    name: 'Medalha 3D Personalizada',
    shortDescription: 'Medalhas Ãºnicas para seus eventos e competiÃ§Ãµes',
    description: 'Medalhas impressas em 3D para corridas, jogos escolares, campeonatos e eventos corporativos. Personalize com seu logo, data e texto. MÃ­nimo 20 unidades.',
    price: 18.90,
    category: 'produtos-3d',
    subcategory: 'Medalhas',
    images: [
      { id: 'img-010', url: '/images/3d-medal.svg', alt: 'Medalha 3D', color: '#FFB800' },
    ],
    colors: [
      { name: 'Ouro', hex: '#FFB800' },
      { name: 'Prata', hex: '#C0C0C0' },
      { name: 'Bronze', hex: '#CD7F32' },
      { name: 'Preto', hex: '#1A1A1A' },
    ],
    sizes: [{ label: 'Ãšnico', available: true }],
    status: 'available',
    tags: ['bestseller'],
    rating: 4.9,
    reviewCount: 234,
    isPersonalizable: true,
    isFeatured: true,
    isNew: false,
    stock: 999,
    sku: '3D-002-MED',
    material: 'PLA Premium / ABS',
    weight: 0.08,
    createdAt: '2024-01-01',
  },

  // GEEK
  {
    id: 'gk-001',
    slug: 'pokemon-booster-box-scarlet-violet',
    name: 'Booster Box Scarlet & Violet',
    shortDescription: '36 boosters do set Scarlet & Violet lacrado',
    description: 'Box lacrada com 36 boosters do set Scarlet & Violet. Produto oficial PokÃ©mon Company. Cada booster contÃ©m 10 cartas incluindo ao menos 1 rara ou superior.',
    price: 849.90,
    category: 'geek',
    subcategory: 'PokÃ©mon TCG',
    images: [
      { id: 'img-011', url: '/images/pokemon-booster-box.svg', alt: 'Booster Box Scarlet & Violet', color: '#CC2200' },
    ],
    colors: [],
    sizes: [{ label: 'Lacrado', available: true }],
    status: 'low_stock',
    tags: ['exclusive', 'limited'],
    rating: 4.9,
    reviewCount: 89,
    isPersonalizable: false,
    isFeatured: true,
    isNew: false,
    stock: 8,
    sku: 'GK-001-PKSV',
    weight: 1.2,
    createdAt: '2024-01-10',
  },
  {
    id: 'gk-002',
    slug: 'pokemon-triple-pack-sv',
    name: 'Triple Pack Scarlet & Violet',
    shortDescription: '3 boosters + 1 carta promocional exclusiva',
    description: 'Triple Pack com 3 boosters Scarlet & Violet + 1 carta promocional exclusiva estampada. Produto oficial lacrado.',
    price: 89.90,
    category: 'geek',
    subcategory: 'PokÃ©mon TCG',
    images: [
      { id: 'img-012', url: '/images/pokemon-triple-pack.svg', alt: 'Triple Pack PokÃ©mon', color: '#E05A00' },
    ],
    colors: [],
    sizes: [{ label: 'Lacrado', available: true }],
    status: 'available',
    tags: ['new'],
    rating: 4.8,
    reviewCount: 156,
    isPersonalizable: false,
    isFeatured: false,
    isNew: true,
    stock: 43,
    sku: 'GK-002-PKTPL',
    weight: 0.15,
    createdAt: '2024-04-01',
  },
]

export const FEATURED_PRODUCTS = MOCK_PRODUCTS.filter(p => p.isFeatured)

export const NEW_PRODUCTS = MOCK_PRODUCTS.filter(p => p.isNew)

export function getProductsByCategory(category: string): Product[] {
  return MOCK_PRODUCTS.filter(p => p.category === category)
}

export function getProductBySlug(slug: string): Product | undefined {
  return MOCK_PRODUCTS.find(p => p.slug === slug)
}

export function getProductById(id: string): Product | undefined {
  return MOCK_PRODUCTS.find(p => p.id === id)
}

export const KITS: KitProduct[] = [
  {
    id: 'kit-001',
    name: 'Kit Empresa BÃ¡sico',
    slug: 'kit-empresa-basico',
    description: 'Ideal para uniformizar sua equipe com estilo e profissionalismo. Personalize com sua identidade visual completa.',
    targetAudience: 'Empresas e Startups',
    minQuantity: 10,
    basePrice: 79.90,
    items: [
      'Camiseta personalizada com logo',
      'Escolha de cor e tamanho individual',
      'Arte inclusa (atÃ© 2 cores)',
      'Embalagem individual',
      'Prazo de 7 dias Ãºteis',
    ],
    popular: false,
  },
  {
    id: 'kit-002',
    name: 'Kit Academia / CrossFit',
    slug: 'kit-academia',
    description: 'Uniforme completo para academias, boxe, crossfit e artes marciais. Tecido dry-fit premium com sua marca.',
    targetAudience: 'Academias e Studios',
    minQuantity: 20,
    basePrice: 89.90,
    items: [
      'Camiseta dry-fit personalizada',
      'Shorts ou legging (opcional)',
      'Bordado ou sublimaÃ§Ã£o total',
      'Tamanhos PP ao XGG',
      'Entrega em 10 dias Ãºteis',
    ],
    popular: true,
  },
  {
    id: 'kit-003',
    name: 'Kit Escola / Interclasse',
    slug: 'kit-escola-interclasse',
    description: 'Camisetas para jogos internos, excursÃµes e eventos escolares. Diversas cores para diferentes turmas.',
    targetAudience: 'Escolas e Universidades',
    minQuantity: 30,
    basePrice: 49.90,
    items: [
      'Camiseta colorida personalizada',
      'Silk ou sublimaÃ§Ã£o',
      'Diversas cores por turma/time',
      'NumeraÃ§Ã£o individual (opcional)',
      'Prazo de 7 a 10 dias Ãºteis',
    ],
    popular: false,
  },
  {
    id: 'kit-004',
    name: 'Kit Evento',
    slug: 'kit-evento',
    description: 'Para shows, festivais, conferÃªncias e lanÃ§amentos. Crie um item exclusivo que os participantes vÃ£o querer guardar.',
    targetAudience: 'Eventos e Produtoras',
    minQuantity: 50,
    basePrice: 59.90,
    items: [
      'Camiseta colecionÃ¡vel do evento',
      'Design exclusivo pela nossa equipe',
      'Oversized ou regular',
      'Embalagem temÃ¡tica (opcional)',
      'Prazo negociÃ¡vel conforme quantidade',
    ],
    popular: true,
  },
  {
    id: 'kit-005',
    name: 'Kit Corrida',
    slug: 'kit-corrida',
    description: 'Camiseta tÃ©cnica dry-fit para corredores com nÃºmero de atleta e personalizaÃ§Ã£o da prova.',
    targetAudience: 'OrganizaÃ§Ã£o de Corridas',
    minQuantity: 100,
    basePrice: 39.90,
    items: [
      'Camiseta dry-fit tÃ©cnica',
      'NÃºmero de atleta sublimado',
      'Nome do corredor (opcional)',
      'Cores personalizÃ¡veis',
      'Volumes grandes com desconto',
    ],
    popular: false,
  },
  {
    id: 'kit-006',
    name: 'Kit Brindes 3D',
    slug: 'kit-brindes-3d',
    description: 'Brindes impressos em 3D para eventos corporativos: chaveiros, porta-cartÃµes, trofÃ©us e muito mais.',
    targetAudience: 'Empresas e Eventos',
    minQuantity: 20,
    items: [
      'Chaveiros personalizados em 3D',
      'Porta-cartÃµes com logo',
      'TrofÃ©us e placas',
      'Embalagem premium',
      'Cores diversas disponÃ­veis',
    ],
    popular: false,
  },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'test-001',
    name: 'Rafael Mendes',
    city: 'SÃ£o Paulo, SP',
    rating: 5,
    text: 'Qualidade absurda! A camiseta oversized chegou perfeita, tecido premium de verdade. JÃ¡ pedi mais 3. A personalizaÃ§Ã£o ficou exatamente como eu queria.',
    product: 'Drop Black Oversized',
    date: '2024-03-15',
  },
  {
    id: 'test-002',
    name: 'Camila Torres',
    city: 'Belo Horizonte, MG',
    rating: 5,
    text: 'Fiz o kit para minha academia e todo mundo adorou! Qualidade da dry-fit Ã© diferenciada, o prazo foi cumprido e a arte ficou incrÃ­vel. Recomendo demais!',
    product: 'Kit Academia',
    date: '2024-02-28',
  },
  {
    id: 'test-003',
    name: 'Lucas Ferreira',
    city: 'Rio de Janeiro, RJ',
    rating: 5,
    text: 'Os chaveiros 3D do evento ficaram show de bola! Todo mundo quis levar um. A StreetDrop entregou antes do prazo e a qualidade superou minhas expectativas.',
    product: 'Chaveiros 3D',
    date: '2024-04-01',
  },
  {
    id: 'test-004',
    name: 'Ana Paula Costa',
    city: 'Curitiba, PR',
    rating: 5,
    text: 'Comprei cartas PokÃ©mon e veio tudo lacrado, embalagem top. A camiseta oversized que peguei junto Ã© minha favorita agora. Atendimento nota 10!',
    product: 'Geek Store + Oversized',
    date: '2024-03-22',
  },
  {
    id: 'test-005',
    name: 'Marcos Oliveira',
    city: 'Porto Alegre, RS',
    rating: 5,
    text: 'Pedi camisetas para o interclasse da escola. Chegaram no prazo, preÃ§o justo e as camisetas ficaram lindas! Os alunos amaram as cores diferentes por turma.',
    product: 'Kit Escola',
    date: '2024-02-10',
  },
  {
    id: 'test-006',
    name: 'Julia Santos',
    city: 'Salvador, BA',
    rating: 4,
    text: 'Muito satisfeita com a qualidade. A camiseta classic preta Ã© aquela peÃ§a coringa que uso com tudo. Entrega rÃ¡pida e bem embalada. Voltarei a comprar!',
    product: 'Classic Black',
    date: '2024-04-05',
  },
]

export const FAQS = [
  {
    id: 'faq-001',
    question: 'Como funciona a personalizaÃ§Ã£o das camisetas?',
    answer: 'Ã‰ simples! Escolha o produto, clique em "Personalizar", faÃ§a upload da sua arte (ou escolha uma das nossas estampas), selecione posiÃ§Ã£o, cor e tamanho. Nossa equipe analisa o arquivo e produz com precisÃ£o profissional.',
  },
  {
    id: 'faq-002',
    question: 'Qual o prazo de entrega?',
    answer: 'Produtos prontos (sem personalizaÃ§Ã£o) sÃ£o entregues em 3-7 dias Ãºteis. Produtos personalizados levam de 7-12 dias Ãºteis para produÃ§Ã£o + prazo de entrega. Kits para empresas tÃªm prazo combinado conforme quantidade.',
  },
  {
    id: 'faq-003',
    question: 'Qual o tamanho mÃ­nimo para kits?',
    answer: 'Para camisetas personalizadas, o mÃ­nimo Ã© 10 unidades. Para kits completos de empresa ou academia, mÃ­nimo de 20 unidades. Para eventos e corridas, a partir de 50 unidades com descontos progressivos.',
  },
  {
    id: 'faq-004',
    question: 'Quais formatos de arquivo aceitam?',
    answer: 'Aceitamos PNG (fundo transparente, mÃ­nimo 300dpi), AI, CDR, PDF vetorial e PSD em alta resoluÃ§Ã£o. Para melhores resultados, recomendamos arquivos vetoriais. Nossa equipe pode adaptar artes simples sem custo adicional.',
  },
  {
    id: 'faq-005',
    question: 'As camisetas encolhem na lavagem?',
    answer: 'Nossas camisetas passam por prÃ©-lavagem industrial, reduzindo o encolhimento para menos de 3%. Recomendamos lavar a frio, nÃ£o usar secadora e nÃ£o torcer. Assim sua peÃ§a dura muito mais tempo.',
  },
  {
    id: 'faq-006',
    question: 'Posso devolver ou trocar?',
    answer: 'Produtos prontos (sem personalizaÃ§Ã£o) tÃªm 7 dias para troca por defeito. Produtos personalizados nÃ£o tÃªm troca por arrependimento, mas garantimos reposiÃ§Ã£o em caso de defeito de impressÃ£o ou confecÃ§Ã£o comprovado.',
  },
  {
    id: 'faq-007',
    question: 'Os produtos PokÃ©mon TCG sÃ£o originais?',
    answer: 'Sim! Todos os produtos PokÃ©mon TCG vendidos sÃ£o originais e lacrados, adquiridos de distribuidores autorizados. Cartas avulsas sÃ£o originais e devidamente classificadas por condiÃ§Ã£o. Nota fiscal em todas as compras.',
  },
  {
    id: 'faq-008',
    question: 'VocÃªs fazem frete grÃ¡tis?',
    answer: 'Sim! Compras acima de R$ 199,90 tÃªm frete grÃ¡tis para todo o Brasil. Abaixo deste valor, o frete Ã© calculado no checkout por CEP com as melhores opÃ§Ãµes dos Correios e transportadoras parceiras.',
  },
]

export const MOCK_ORDERS: Order[] = [
  {
    id: 'ord-001',
    orderNumber: 'SD-2024-00847',
    userId: 'user-001',
    items: [
      {
        product: MOCK_PRODUCTS[0],
        quantity: 2,
        selectedColor: { name: 'Preto', hex: '#1A1A1A' },
        selectedSize: { label: 'G', available: true },
        customization: { stampName: 'Logo Empresarial', position: 'Frente Central' },
      },
    ],
    subtotal: 179.80,
    shipping: 0,
    discount: 0,
    total: 179.80,
    status: 'delivered',
    paymentMethod: 'CartÃ£o de CrÃ©dito',
    paymentStatus: 'paid',
    shippingAddress: {
      id: 'addr-001',
      label: 'Casa',
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apto 45',
      neighborhood: 'Jardim Paulista',
      city: 'SÃ£o Paulo',
      state: 'SP',
      zipCode: '01310-100',
      isDefault: true,
    },
    trackingCode: 'BR123456789',
    estimatedDelivery: '2024-04-10',
    createdAt: '2024-04-01',
    updatedAt: '2024-04-09',
  },
  {
    id: 'ord-002',
    orderNumber: 'SD-2024-00923',
    userId: 'user-001',
    items: [
      {
        product: MOCK_PRODUCTS[5],
        quantity: 3,
        selectedColor: { name: 'Preto', hex: '#0D0D0D' },
        selectedSize: { label: 'M', available: true },
      },
    ],
    subtotal: 239.70,
    shipping: 0,
    discount: 0,
    total: 239.70,
    status: 'in_production',
    paymentMethod: 'PIX',
    paymentStatus: 'paid',
    shippingAddress: {
      id: 'addr-001',
      label: 'Casa',
      street: 'Rua das Flores',
      number: '123',
      complement: 'Apto 45',
      neighborhood: 'Jardim Paulista',
      city: 'SÃ£o Paulo',
      state: 'SP',
      zipCode: '01310-100',
      isDefault: true,
    },
    estimatedDelivery: '2024-04-20',
    createdAt: '2024-04-12',
    updatedAt: '2024-04-13',
  },
]
